return {
    {
        name = 'smoke',
        sprite = 'smoke',
        depthMin = 1,
        depthMax = 3,
        lifetimeMin = 0.2,
        lifetimeMax = 0.4,
        particlesPerSecond = 100,
        maxAlive = 5,
        speedMin = 100,
        speedMax = 120,
        angle = 45,
        angleDispersion = 60,
        scaleMin = 0.25,
        scaleMax = 0.5,
        scaleSpeedMin = -0.25,
        scaleSpeedMax = 0,
        rotation = 0,
        rotationDispersion = 360,
        rotationSpeedMin = 90,
        rotationSpeedMax = 180,
    },
    {
        name = 'hit',
        sprite = 'hit',
        depthMin = -7,
        depthMax = -5,
        lifetimeMin = 0.1,
        lifetimeMax = 0.2,
        particlesPerSecond = 100,
        maxAlive = 10,
        speedMin = 80,
        speedMax = 100,
        angle = 0,
        angleDispersion = 360,
        scaleMin = 0.25,
        scaleMax = 0.5,
        scaleSpeedMin = -0.25,
        scaleSpeedMax = 0,
        rotation = 0,
        rotationDispersion = 30,
        rotationSpeedMin = -45,
        rotationSpeedMax = 45,
    }
};